export enum ProductType {
    SAVINGS_ACCOUNT = 'DEPOSIT_ACCOUNT',
    CHECKING_ACCOUNT = 'CURRENT_ACCOUNT',
    CDT = 'CERTIFIED_DEPOSIT_TERM',
    CREDIT = 'CREDIT',
    CREDIT_CARD = 'CREDIT_CARD'
}